spring.application.name=project-gym
app.console.enabled=true

db.url=jdbc:postgresql://localhost:5432/gymcrm
db.username=postgres
db.password=postgres
db.driver=org.postgresql.Driver

hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
hibernate.hbm2ddl.auto=create-drop
hibernate.show_sql=true
hibernate.format_sql=true